<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\DatabaseMigrations;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;
use App\Item;

class ItemTest extends TestCase
{
    use DatabaseMigrations;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $seeder = new \DatabaseSeeder();
        $seeder->run();
    }

    public function testIndex()
    {
        $response = $this->get('/api/items');
        $this->assertCount(1, $response->json());
    }

    public function testShow()
    {
        $response = $this->get('/api/items/1');
        $response->assertStatus(200);
    }

    public function testStore()
    {
        $data = ['content' => 'ブログを書く'];
        $response = $this->post('/api/items', $data);

        $response->assertStatus(201);
        $response->assertJson($data);

    }

    public function testUpdateContent()
    {
        $data = ['content' => 'ブログを書く'];
        $response = $this->patch('/api/items/1', $data);

        $response->assertStatus(200);
        $response->assertJson($data);
        $item = Item::query()->find(1);
        $this->assertSame('ブログを書く', $item->content);
    }

    public function testUpdateChecked()
    {
        $data = ['checked' => 1];
        $response = $this->patch('/api/items/1', $data);

        $response->assertStatus(200);
        $response->assertJson($data);
        $item = Item::query()->find(1);
        $this->assertEquals(true, $item->checked);
    }

    public function testDelete()
    {
        $response = $this->delete('/api/items/1');

        $response->assertStatus(200);
        $this->assertNull(Item::query()->find(1));
    }
}
